---
- name: Configure AWS credentials
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0640
    backup: yes
  with_items:
    - { src: 'config.j2', dest: '$HOME/.aws/config' }
    - { src: 'credentials.j2', dest: '$HOME/.aws/credentials' }
    - { src: 'extend_switch_roles.j2', dest: '$HOME/.aws/extend_switch_roles.ini' }
    - { src: 'firefox_containers.j2', dest: '$HOME/.aws/firefox_containers.csv' }
